export const dairies = [
  'american cheese',
  'blue cheese',
  'brie',
  'butter',
  'buttermilk',
  'camembert cheese',
  'cheddar',
  'colby cheese',
  'condensed milk',
  'cottage cheese',
  'cream',
  'cream cheese',
  'custard',
  'edam cheese',
  'egg',
  'farmer cheese',
  'feta',
  'fontina',
  'frosting',
  'ghee',
  'goat cheese',
  'goat milk',
  'gouda',
  'gruyere',
  'half and half',
  'halloumi',
  'hard cheese',
  'ice cream',
  'italian cheese',
  'manchego',
  'milk',
  'monterey jack cheese',
  'mozzarella',
  'parmesan',
  'pecorino cheese',
  'pepper jack',
  'pepperjack cheese',
  'pizza cheese',
  'powdered milk',
  'aclette cheese',
  'ricotta',
  'soft cheese',
  'sour cream',
  'swiss cheese',
  'whipped cream',
  'yogurt',
];
export const vegtables = [
  'artichoke',
  'artichoke heart',
  'arugula',
  'asparagus',
  'avocado',
  'bamboo shoot',
  'basil',
  'bean sprouts',
  'beet',
  'bell pepper',
  'bok choy',
  'broccoli',
  'broccoli rabe',
  'brussels sprout',
  'burdock',
  'butternut',
  'butternut squash',
  'cabbage',
  'canned tomato',
  'caper',
  'capsicum',
  'carrot',
  'cauliflower',
  'celery',
  'celery root',
  'chard',
  'chayote',
  'chia seeds',
  'chili pepper',
  'chinese broccoli',
  'cilantro',
  'collard',
  'corn',
  'cress',
  'cucumber',
  'daikon',
  'dill',
  'dulse',
  'eggplant',
  'endive',
  'fennel',
  'frozen vegetables',
  'garlic',
  'ginger',
  'green beans',
  'hearts of palm',
  'horseradish',
  'jerusalem artichoke',
  'jicama',
  'kale',
  'kohlrabi',
  'leek',
  'micro greens',
  'mint',
  'mixed vegetable',
  'mushroom',
  'mustard greens',
  'okra',
  'olive',
  'onion',
  'parsley',
  'parsnip',
  'pickle',
  'pimiento',
  'porcini',
  'portobello mushroom',
  'potato',
  'pumpkin',
  'radicchio',
  'radish',
  'red onion',
  'rocket',
  'rosemary',
  'rutabaga',
  'salad greens',
  'sauerkraut',
  'scallion',
  'seaweed',
  'shallot',
  'snow peas',
  'spaghetti squash',
  'spinach',
  'squash',
  'sun dried tomato',
  'sweet pepper',
  'sweet potato',
  'tomatillo',
  'tomato',
  'turnip',
  'water chestnut',
  'watercress',
  'yam',
  'zucchini',
];
export const fruits = [
  'apple',
  'apple butter',
  'apricot',
  'banana',
  'berries',
  'blackberry',
  'blueberry',
  'boysenberry',
  'cantaloupe',
  'cherry',
  'clementine',
  'coconut',
  'crabapples',
  'craisins',
  'cranberry',
  'currant',
  'date',
  'fig',
  'grape',
  'grapefruit',
  'guava',
  'honeydew',
  'kiwi',
  'kumquat',
  'lemon',
  'lime',
  'lingonberry',
  'lychee',
  'mandarin',
  'mango',
  'nectarine',
  'orange',
  'papaya',
  'passion fruit',
  'peach',
  'pear',
  'persimmons',
  'pineapple',
  'plantain',
  'plum',
  'pomegranate',
  'prunes',
  'quince',
  'raisin',
  'raspberry',
  'rhubarb',
  'star fruit',
  'strawberry',
  'sultanas',
  'tangelos',
  'tangerine',
  'watermelon',
];
export const grains = [
  'angel food',
  'angel hair',
  'bagel',
  'baguette',
  'baking powder',
  'baking soda',
  'barley',
  'bicarbonate of soda',
  'biscuits',
  'bisquick',
  'bran',
  'bread',
  'bread crumbs',
  'bread dough',
  'bread flour',
  'breadsticks',
  'brown rice',
  'buckwheat',
  'cake mix',
  'cereal',
  'challah',
  'chips',
  'ciabatta',
  'coconut flake',
  'coconut flour',
  'corn tortillas',
  'cornbread',
  'cornflour',
  'cornmeal',
  'cornstarch',
  'couscous',
  'cracker',
  'cream of wheat',
  'crescent roll dough',
  'croissants',
  'croutons',
  'english muffin',
  'filo dough',
  'flour',
  'flour tortillas',
  'gnocchi',
  'gram flour',
  'hot dog bun',
  'lasagne',
  'macaroni cheese mix',
  'malt extract',
  'matzo meal',
  'muffin mix',
  'multigrain bread',
  'noodle',
  'pancake mix',
  'pasta',
  'pie crust',
  'pierogi',
  'pita',
  'pizza dough',
  'polenta',
  'popcorn',
  'potato flakes',
  'potato starch',
  'pretzel',
  'puff pastry',
  'quinoa',
  'ramen',
  'ravioli',
  'rice',
  'rice flour',
  'risotto',
  'rolled oats',
  'rye',
  'saltines',
  'self rising flour',
  'semolina',
  'shortcrust pastry',
  'sorghum flour',
  'sourdough starter',
  'spelt',
  'sponge cake',
  'starch',
  'stuffing mix',
  'tapioca flour',
  'tapioca starch',
  'vermicelli',
  'wafer',
  'wheat',
  'wheat germ',
  'whole wheat flour',
  'yeast',
  'yeast flake',
];
export const meats = [
  'alligator',
  'bacon',
  'beef liver',
  'beef ribs',
  'beef roast',
  'beef shank',
  'beef sirloin',
  'beef steak',
  'beef suet',
  'bologna',
  'bratwurst',
  'canadian bacon',
  'chicken breast',
  'chicken giblets',
  'chicken leg',
  'chicken roast',
  'chicken tenders',
  'chicken thighs',
  'chicken wings',
  'chorizo',
  'cooked chicken',
  'corned beef',
  'cornish hen',
  'deer',
  'duck',
  'duck liver',
  'elk',
  'foie gras',
  'goose',
  'goose liver',
  'ground beef',
  'ground chicken',
  'ground lamb',
  'ground pork',
  'ground turkey',
  'ground veal',
  'grouse',
  'ham',
  'hot dog',
  'lamb',
  'lamb chops',
  'lamb liver',
  'lamb loin',
  'lamb shank',
  'lamb shoulder',
  'leg of lamb',
  'liver sausage',
  'marrow bones',
  'moose',
  'ostrich',
  'oxtail',
  'pancetta',
  'pastrami',
  'pepperoni',
  'pheasant',
  'pigeon',
  'polish sausage',
  'pork',
  'pork belly',
  'pork chops',
  'pork liver',
  'pork loin',
  'pork ribs',
  'pork roast',
  'pork shoulder',
  'prosciutto',
  'quail',
  'rabbit',
  'salami',
  'sausage',
  'sliced turkey',
  'snail',
  'soppressata',
  'spam',
  'sweetbread',
  'turkey',
  'turkey liver',
  'veal',
  'veal chops',
  'veal cutlet',
  'veal shank',
  'venison',
  'whole chicken',
  'wild boar',
];
export const fishes = [
  'canned tuna',
  'salmon',
  'tilapia',
  'fish fillets',
  'cod',
  'canned salmon',
  'anchovy',
  'smoked salmon',
  'sardines',
  'tuna steak',
  'whitefish',
  'halibut',
  'trout',
  'haddock',
  'flounder',
  'catfish',
  'mahi mahi',
  'mackerel',
  'sole',
  'sea bass',
  'red snapper',
  'swordfish',
  'pollock',
  'herring',
  'perch',
  'grouper',
  'caviar',
  'monkfish',
  'rockfish',
  'lemon sole',
  'pike',
  'barramundi',
  'eel',
  'bluefish',
  'carp',
  'cuttlefish',
  'pompano',
  'arctic char',
  'john dory',
  'marlin',
  'amberjack',
  'sturgeon',
];
export const seaFoods = [
  'shrimp',
  'crab',
  'prawns',
  'scallop',
  'clam',
  'lobster',
  'mussel',
  'oyster',
  'squid',
  'calamari',
  'crawfish',
  'octopus',
  'cockle',
  'conch',
  'sea urchin',
];
export const legumes = [
  'green beans',
  'peas',
  'black beans',
  'chickpea',
  'lentil',
  'refried beans',
  'hummus',
  'chili beans',
  'lima beans',
  'kidney beans',
  'pinto beans',
  'edamame',
  'split peas',
  'snap peas',
  'soybeans',
  'cannellini beans',
  'navy beans',
  'french beans',
  'red beans',
  'great northern beans',
  'fava beans',
];
